### ISSUE TITLE
Test failure of PyKDL. 

### ISSUE THREAD

**Issue by threedee003** [orocos/orocos_kinematics_dynamics#468]
I installed python_orocos_kdl from the master branch using `catkin_make_isolated` cmd. The installation didnt show any error but the test cases are failing. This is terminal output during the `catkin_make_isolated`. 
```
Base path: /home/tribikram/catkin_ws
Source space: /home/tribikram/catkin_ws/src
Build space: /home/tribikram/catkin_ws/build_isolated
Devel space: /home/tribikram/catkin_ws/devel_isolated
Install space: /home/tribikram/catkin_ws/install_isolated
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~  traversing 2 packages in topological order:
~~  - orocos_kdl (plain cmake)
~~  - python_orocos_kdl
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The packages or cmake arguments have changed, forcing cmake invocation

==> Processing plain cmake package: 'orocos_kdl'
==> Creating build directory: 'build_isolated/orocos_kdl/devel'
==> cmake /home/tribikram/catkin_ws/src/orocos_kdl -DCMAKE_INSTALL_PREFIX=/home/tribikram/catkin_ws/devel_isolated/orocos_kdl -G Unix Makefiles in '/home/tribikram/catkin_ws/build_isolated/orocos_kdl/devel'
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Orocos KDL version  (1.5.1)
-- Using CATKIN_DEVEL_PREFIX: /home/tribikram/catkin_ws/build_isolated/orocos_kdl/devel/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/noetic
-- This workspace overlays: /opt/ros/noetic
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Using Debian Python package layout
-- Found PY_em: /usr/lib/python3/dist-packages/em.py  
-- Using empy: /usr/lib/python3/dist-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/tribikram/catkin_ws/build_isolated/orocos_kdl/devel/test_results
-- Forcing gtest/gmock from source, though one was otherwise available.
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.10") 
-- Found Threads: TRUE  
-- Using Python nosetests: /usr/bin/nosetests3
-- catkin 0.8.10
-- BUILD_SHARED_LIBS is on
-- Setting build type to 'Release'
-- Performing Test HAVE_STL_CONTAINER_INCOMPLETE_TYPES
-- Performing Test HAVE_STL_CONTAINER_INCOMPLETE_TYPES - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tribikram/catkin_ws/build_isolated/orocos_kdl/devel
==> make -j12 -l12 in '/home/tribikram/catkin_ws/build_isolated/orocos_kdl/devel'
Scanning dependencies of target orocos-kdl
[  4%] Building CXX object src/CMakeFiles/orocos-kdl.dir/chain.cpp.o
[  4%] Building CXX object src/CMakeFiles/orocos-kdl.dir/chaindynparam.cpp.o
[  4%] Building CXX object src/CMakeFiles/orocos-kdl.dir/articulatedbodyinertia.cpp.o
[  5%] Building CXX object src/CMakeFiles/orocos-kdl.dir/chainfdsolver_recursive_newton_euler.cpp.o
[  7%] Building CXX object src/CMakeFiles/orocos-kdl.dir/chainexternalwrenchestimator.cpp.o
[  8%] Building CXX object src/CMakeFiles/orocos-kdl.dir/chainfksolverpos_recursive.cpp.o
[ 13%] Building CXX object src/CMakeFiles/orocos-kdl.dir/chainhdsolver_vereshchagin.cpp.o
[ 13%] Building CXX object src/CMakeFiles/orocos-kdl.dir/chainidsolver_vereshchagin.cpp.o
[ 13%] Building CXX object src/CMakeFiles/orocos-kdl.dir/chainfksolvervel_recursive.cpp.o
[ 14%] Building CXX object src/CMakeFiles/orocos-kdl.dir/chainidsolver_recursive_newton_euler.cpp.o
[ 16%] Building CXX object src/CMakeFiles/orocos-kdl.dir/chainiksolverpos_lma.cpp.o
[ 17%] Building CXX object src/CMakeFiles/orocos-kdl.dir/chainiksolverpos_nr.cpp.o
[ 19%] Building CXX object src/CMakeFiles/orocos-kdl.dir/chainiksolverpos_nr_jl.cpp.o
[ 20%] Building CXX object src/CMakeFiles/orocos-kdl.dir/chainiksolvervel_pinv.cpp.o
[ 22%] Building CXX object src/CMakeFiles/orocos-kdl.dir/chainiksolvervel_pinv_givens.cpp.o
[ 23%] Building CXX object src/CMakeFiles/orocos-kdl.dir/chainiksolvervel_pinv_nso.cpp.o
[ 25%] Building CXX object src/CMakeFiles/orocos-kdl.dir/chainiksolvervel_wdls.cpp.o
[ 26%] Building CXX object src/CMakeFiles/orocos-kdl.dir/chainjnttojacdotsolver.cpp.o
[ 28%] Building CXX object src/CMakeFiles/orocos-kdl.dir/chainjnttojacsolver.cpp.o
[ 29%] Building CXX object src/CMakeFiles/orocos-kdl.dir/frameacc.cpp.o
[ 31%] Building CXX object src/CMakeFiles/orocos-kdl.dir/frames.cpp.o
[ 32%] Building CXX object src/CMakeFiles/orocos-kdl.dir/frames_io.cpp.o
[ 34%] Building CXX object src/CMakeFiles/orocos-kdl.dir/framevel.cpp.o
[ 35%] Building CXX object src/CMakeFiles/orocos-kdl.dir/jacobian.cpp.o
[ 37%] Building CXX object src/CMakeFiles/orocos-kdl.dir/jntarray.cpp.o
[ 38%] Building CXX object src/CMakeFiles/orocos-kdl.dir/jntarrayacc.cpp.o
[ 40%] Building CXX object src/CMakeFiles/orocos-kdl.dir/jntarrayvel.cpp.o
[ 41%] Building CXX object src/CMakeFiles/orocos-kdl.dir/jntspaceinertiamatrix.cpp.o
[ 43%] Building CXX object src/CMakeFiles/orocos-kdl.dir/joint.cpp.o
[ 44%] Building CXX object src/CMakeFiles/orocos-kdl.dir/kinfam_io.cpp.o
[ 46%] Building CXX object src/CMakeFiles/orocos-kdl.dir/path.cpp.o
[ 47%] Building CXX object src/CMakeFiles/orocos-kdl.dir/path_circle.cpp.o
[ 49%] Building CXX object src/CMakeFiles/orocos-kdl.dir/path_composite.cpp.o
[ 50%] Building CXX object src/CMakeFiles/orocos-kdl.dir/path_cyclic_closed.cpp.o
[ 52%] Building CXX object src/CMakeFiles/orocos-kdl.dir/path_line.cpp.o
[ 53%] Building CXX object src/CMakeFiles/orocos-kdl.dir/path_point.cpp.o
[ 55%] Building CXX object src/CMakeFiles/orocos-kdl.dir/path_roundedcomposite.cpp.o
[ 56%] Building CXX object src/CMakeFiles/orocos-kdl.dir/rigidbodyinertia.cpp.o
[ 58%] Building CXX object src/CMakeFiles/orocos-kdl.dir/rotational_interpolation.cpp.o
[ 59%] Building CXX object src/CMakeFiles/orocos-kdl.dir/rotational_interpolation_sa.cpp.o
[ 61%] Building CXX object src/CMakeFiles/orocos-kdl.dir/rotationalinertia.cpp.o
[ 62%] Building CXX object src/CMakeFiles/orocos-kdl.dir/segment.cpp.o
[ 64%] Building CXX object src/CMakeFiles/orocos-kdl.dir/trajectory.cpp.o
[ 65%] Building CXX object src/CMakeFiles/orocos-kdl.dir/trajectory_composite.cpp.o
[ 67%] Building CXX object src/CMakeFiles/orocos-kdl.dir/trajectory_segment.cpp.o
[ 68%] Building CXX object src/CMakeFiles/orocos-kdl.dir/trajectory_stationary.cpp.o
[ 70%] Building CXX object src/CMakeFiles/orocos-kdl.dir/tree.cpp.o
[ 71%] Building CXX object src/CMakeFiles/orocos-kdl.dir/treefksolverpos_recursive.cpp.o
[ 73%] Building CXX object src/CMakeFiles/orocos-kdl.dir/treeidsolver_recursive_newton_euler.cpp.o
[ 74%] Building CXX object src/CMakeFiles/orocos-kdl.dir/treeiksolverpos_nr_jl.cpp.o
[ 76%] Building CXX object src/CMakeFiles/orocos-kdl.dir/treeiksolverpos_online.cpp.o
[ 77%] Building CXX object src/CMakeFiles/orocos-kdl.dir/treeiksolvervel_wdls.cpp.o
[ 79%] Building CXX object src/CMakeFiles/orocos-kdl.dir/treejnttojacsolver.cpp.o
[ 80%] Building CXX object src/CMakeFiles/orocos-kdl.dir/utilities/error_stack.cxx.o
[ 82%] Building CXX object src/CMakeFiles/orocos-kdl.dir/utilities/ldl_solver_eigen.cpp.o
[ 83%] Building CXX object src/CMakeFiles/orocos-kdl.dir/utilities/svd_HH.cpp.o
[ 85%] Building CXX object src/CMakeFiles/orocos-kdl.dir/utilities/svd_eigen_HH.cpp.o
[ 86%] Building CXX object src/CMakeFiles/orocos-kdl.dir/utilities/svd_eigen_Macie.cpp.o
[ 88%] Building CXX object src/CMakeFiles/orocos-kdl.dir/utilities/utility.cxx.o
[ 89%] Building CXX object src/CMakeFiles/orocos-kdl.dir/utilities/utility_io.cxx.o
[ 91%] Building CXX object src/CMakeFiles/orocos-kdl.dir/velocityprofile.cpp.o
[ 92%] Building CXX object src/CMakeFiles/orocos-kdl.dir/velocityprofile_dirac.cpp.o
[ 94%] Building CXX object src/CMakeFiles/orocos-kdl.dir/velocityprofile_rect.cpp.o
[ 95%] Building CXX object src/CMakeFiles/orocos-kdl.dir/velocityprofile_spline.cpp.o
[ 97%] Building CXX object src/CMakeFiles/orocos-kdl.dir/velocityprofile_trap.cpp.o
[ 98%] Building CXX object src/CMakeFiles/orocos-kdl.dir/velocityprofile_traphalf.cpp.o
[100%] Linking CXX shared library ../devel/lib/liborocos-kdl.so
[100%] Built target orocos-kdl
==> make install in '/home/tribikram/catkin_ws/build_isolated/orocos_kdl/devel'
[100%] Built target orocos-kdl
Install the project...
-- Install configuration: "Release"
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/_setup_util.py
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/env.sh
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/setup.bash
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/local_setup.bash
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/setup.sh
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/local_setup.sh
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/setup.zsh
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/local_setup.zsh
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/.rosinstall
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/share/orocos_kdl/package.xml
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/share/orocos_kdl/cmake/FindEigen3.cmake
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/share/orocos_kdl/cmake/orocos_kdl-config.cmake
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/share/orocos_kdl/cmake/orocos_kdl-config-version.cmake
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/share/orocos_kdl/cmake/OrocosKDLTargets.cmake
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/share/orocos_kdl/cmake/OrocosKDLTargets-release.cmake
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/lib/pkgconfig/orocos-kdl.pc
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/lib/pkgconfig/orocos_kdl.pc
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/lib/liborocos-kdl.so.1.5.1
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/lib/liborocos-kdl.so.1.5
-- Set runtime path of "/home/tribikram/catkin_ws/devel_isolated/orocos_kdl/lib/liborocos-kdl.so.1.5.1" to "$ORIGIN/../lib"
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/lib/liborocos-kdl.so
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/articulatedbodyinertia.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chain.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chaindynparam.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chainexternalwrenchestimator.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chainfdsolver.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chainfdsolver_recursive_newton_euler.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chainfksolver.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chainfksolverpos_recursive.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chainfksolvervel_recursive.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chainhdsolver_vereshchagin.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chainidsolver.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chainidsolver_recursive_newton_euler.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chainidsolver_vereshchagin.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chainiksolver.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chainiksolverpos_lma.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chainiksolverpos_nr.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chainiksolverpos_nr_jl.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chainiksolvervel_pinv.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chainiksolvervel_pinv_givens.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chainiksolvervel_pinv_nso.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chainiksolvervel_wdls.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chainjnttojacdotsolver.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/chainjnttojacsolver.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/frameacc.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/frameacc.inl
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/frameacc_io.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/frames.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/frames.inl
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/frames_io.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/framevel.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/framevel.inl
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/framevel_io.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/jacobian.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/jntarray.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/jntarrayacc.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/jntarrayvel.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/jntspaceinertiamatrix.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/joint.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/kdl.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/kinfam.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/kinfam_io.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/motion.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/path.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/path_circle.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/path_composite.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/path_cyclic_closed.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/path_line.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/path_point.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/path_roundedcomposite.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/rigidbodyinertia.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/rotational_interpolation.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/rotational_interpolation_sa.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/rotationalinertia.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/segment.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/solveri.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/stiffness.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/trajectory.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/trajectory_composite.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/trajectory_segment.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/trajectory_stationary.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/tree.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/treefksolver.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/treefksolverpos_recursive.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/treeidsolver.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/treeidsolver_recursive_newton_euler.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/treeiksolver.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/treeiksolverpos_nr_jl.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/treeiksolverpos_online.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/treeiksolvervel_wdls.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/treejnttojacsolver.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/velocityprofile.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/velocityprofile_dirac.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/velocityprofile_rect.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/velocityprofile_spline.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/velocityprofile_trap.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/velocityprofile_traphalf.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/config.h
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/utilities/error.h
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/utilities/error_stack.h
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/utilities/hash_combine.h
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/utilities/kdl-config.h
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/utilities/ldl_solver_eigen.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/utilities/rall1d.h
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/utilities/rall1d_io.h
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/utilities/rall2d.h
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/utilities/rall2d_io.h
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/utilities/rallNd.h
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/utilities/scoped_ptr.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/utilities/svd_HH.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/utilities/svd_eigen_HH.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/utilities/svd_eigen_Macie.hpp
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/utilities/traits.h
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/utilities/utility.h
-- Installing: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl/include/kdl/utilities/utility_io.h
==> Generating an env.sh
<== Finished processing package [1 of 2]: 'orocos_kdl'

==> Processing catkin package: 'python_orocos_kdl'
==> Building with env: '/home/tribikram/catkin_ws/devel_isolated/orocos_kdl/env.sh'
==> cmake /home/tribikram/catkin_ws/src/python_orocos_kdl -DCATKIN_DEVEL_PREFIX=/home/tribikram/catkin_ws/devel_isolated/python_orocos_kdl -DCMAKE_INSTALL_PREFIX=/home/tribikram/catkin_ws/install_isolated -G Unix Makefiles in '/home/tribikram/catkin_ws/build_isolated/python_orocos_kdl'
-- Found Python: /usr/bin/python3.8 (found suitable version "3.8.10", minimum required is "3") found components: Interpreter Development 
-- Using CATKIN_DEVEL_PREFIX: /home/tribikram/catkin_ws/devel_isolated/python_orocos_kdl
-- Using CMAKE_PREFIX_PATH: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl;/opt/ros/noetic
-- This workspace overlays: /home/tribikram/catkin_ws/devel_isolated/orocos_kdl;/opt/ros/noetic
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Using Debian Python package layout
-- Found PY_em: /usr/lib/python3/dist-packages/em.py  
-- Using empy: /usr/lib/python3/dist-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/tribikram/catkin_ws/build_isolated/python_orocos_kdl/test_results
-- Forcing gtest/gmock from source, though one was otherwise available.
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.10") 
-- Found Threads: TRUE  
-- Using Python nosetests: /usr/bin/nosetests3
-- catkin 0.8.10
-- BUILD_SHARED_LIBS is on
-- pybind11 not found, building from source
-- pybind11 v2.14.0 dev1
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tribikram/catkin_ws/build_isolated/python_orocos_kdl
==> make -j12 -l12 in '/home/tribikram/catkin_ws/build_isolated/python_orocos_kdl'
Scanning dependencies of target PyKDL
[ 33%] Building CXX object CMakeFiles/PyKDL.dir/PyKDL/PyKDL.cpp.o
[ 33%] Building CXX object CMakeFiles/PyKDL.dir/PyKDL/frames.cpp.o
[ 50%] Building CXX object CMakeFiles/PyKDL.dir/PyKDL/kinfam.cpp.o
[ 66%] Building CXX object CMakeFiles/PyKDL.dir/PyKDL/framevel.cpp.o
[ 83%] Building CXX object CMakeFiles/PyKDL.dir/PyKDL/dynamics.cpp.o
[100%] Linking CXX shared module /home/tribikram/catkin_ws/devel_isolated/python_orocos_kdl/lib/python3/dist-packages/PyKDL.so
[100%] Built target PyKDL
<== Finished processing package [2 of 2]: 'python_orocos_kdl'

```

During the tests there are errors.
```
tribikram@tribikramHp:~/catkin_ws/src/python_orocos_kdl/tests$ python3 kinfamtest.py 
testRotationalInertia (__main__.KinfamTestFunctions) ... ERROR
testJacobian (__main__.KinfamTestFunctions) ... ERROR
testJntArray (__main__.KinfamTestFunctions) ... ERROR
testFkPosAndJac (__main__.KinfamTestFunctions) ... ERROR
testFkVelAndJac (__main__.KinfamTestFunctions) ... ERROR
testFkVelAndIkVel (__main__.KinfamTestFunctions) ... ERROR
testFkVelAndIkVelGivens (__main__.KinfamTestFunctions) ... ERROR
testFkPosAndIkPos (__main__.KinfamTestFunctions) ... ERROR
testFkPosAndIkPosGivens (__main__.KinfamTestFunctions) ... ERROR
testJacDot (__main__.KinfamTestFunctions) ... ERROR
testTreeGetChainMemLeak (__main__.KinfamTestTree) ... ERROR

======================================================================
ERROR: testRotationalInertia (__main__.KinfamTestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "kinfamtest.py", line 58, in setUp
    self.chain.addSegment(Segment(Joint(Joint.Fixed),
AttributeError: type object 'Joint' has no attribute 'Fixed'

======================================================================
ERROR: testJacobian (__main__.KinfamTestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "kinfamtest.py", line 58, in setUp
    self.chain.addSegment(Segment(Joint(Joint.Fixed),
AttributeError: type object 'Joint' has no attribute 'Fixed'

======================================================================
ERROR: testJntArray (__main__.KinfamTestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "kinfamtest.py", line 58, in setUp
    self.chain.addSegment(Segment(Joint(Joint.Fixed),
AttributeError: type object 'Joint' has no attribute 'Fixed'

======================================================================
ERROR: testFkPosAndJac (__main__.KinfamTestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "kinfamtest.py", line 58, in setUp
    self.chain.addSegment(Segment(Joint(Joint.Fixed),
AttributeError: type object 'Joint' has no attribute 'Fixed'

======================================================================
ERROR: testFkVelAndJac (__main__.KinfamTestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "kinfamtest.py", line 58, in setUp
    self.chain.addSegment(Segment(Joint(Joint.Fixed),
AttributeError: type object 'Joint' has no attribute 'Fixed'

======================================================================
ERROR: testFkVelAndIkVel (__main__.KinfamTestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "kinfamtest.py", line 58, in setUp
    self.chain.addSegment(Segment(Joint(Joint.Fixed),
AttributeError: type object 'Joint' has no attribute 'Fixed'

======================================================================
ERROR: testFkVelAndIkVelGivens (__main__.KinfamTestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "kinfamtest.py", line 58, in setUp
    self.chain.addSegment(Segment(Joint(Joint.Fixed),
AttributeError: type object 'Joint' has no attribute 'Fixed'

======================================================================
ERROR: testFkPosAndIkPos (__main__.KinfamTestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "kinfamtest.py", line 58, in setUp
    self.chain.addSegment(Segment(Joint(Joint.Fixed),
AttributeError: type object 'Joint' has no attribute 'Fixed'

======================================================================
ERROR: testFkPosAndIkPosGivens (__main__.KinfamTestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "kinfamtest.py", line 58, in setUp
    self.chain.addSegment(Segment(Joint(Joint.Fixed),
AttributeError: type object 'Joint' has no attribute 'Fixed'

======================================================================
ERROR: testJacDot (__main__.KinfamTestFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "kinfamtest.py", line 58, in setUp
    self.chain.addSegment(Segment(Joint(Joint.Fixed),
AttributeError: type object 'Joint' has no attribute 'Fixed'

======================================================================
ERROR: testTreeGetChainMemLeak (__main__.KinfamTestTree)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "kinfamtest.py", line 331, in setUp
    self.tree.addSegment(Segment(Joint(Joint.Fixed),
AttributeError: type object 'Joint' has no attribute 'Fixed'

----------------------------------------------------------------------
Ran 11 tests in 0.001s

FAILED (errors=11)
```

Is there something wrong that I have done ?

@MatthijsBurgh

**Comment by MatthijsBurgh** [comment]
I have not used the old catkin, I have only used [`catkin_tools`](https://github.com/catkin/catkin_tools).

But before using a different catkin, add some print statements to get the path of the PyKDL library. Your python might be importing the incorrect one. Also make sure you resource your workspace after building.

**Comment by threedee003** [comment]
Thank you. It's solved. I used `catkin build` and source the workspace.
